[project]
name = "airflow-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faker>=37.12.0",
    "mysql-connector-python>=9.5.0",
    "pandas>=2.3.3",
]
